
server:
  port: 8088

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dingke?serverTimezone=UTC
    username: root
    password: 123456   #DINGke@666
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5     # 初始化时建立物理连接的个数
      max-active: 20      # 最大连接池数量
      min-idle: 5         # 最小连接池数量
      max-wait: 60000     # 获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis:  60000   # 间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis:  300000     # 一个连接在池中最小的生存时间
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: false
      max-pool-prepared-statement-per-connection-size: 20

  multipart:
    enabled: true
#    max-file-size: 10MB
#    max-request-size: 100MB

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true


logging:
  file:
    path: log/myapp

  redis:
    host: 127.0.0.1
    port: 6379
    #    password: 123456
    timeout: 1000


hadoop:
  host: 192.168.66.153
  port: 50070

